name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --prefix ./frontend

      - name: Build Project
        run: npm run build --prefix ./frontend

      - name: List files in dist directory
        run: ls -la ./frontend/dist

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./frontend/dist
          name: frontend-dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifact_name: frontend-dist
